export { default as FooterView } from './FooterView'
export { default as HeaderView } from './HeaderView'
export { default as MainView } from './MainView'
export { default as SideView} from './SideView'
export { default as LessonHeader} from './lesson/LessonHeader'
